# Generated by Django 5.1.2 on 2024-11-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('MY_DAY', 'My Day'), ('IMPORTANT', 'Important'), ('PLANNED', 'Planned')], default='PLANNED', max_length=20)),
            ],
        ),
    ]
